export const DATASET_ID_PLACEHOLDER = '{datasetId}';
export const CONNECTION_ID_PLACEHOLDER = '{connectionId}';
export const DATASET_DISTINCTS_URL = '/_bi_datasets/{datasetId}/values/distinct';
export const DATASET_FIELDS_URL = '/_bi_datasets/{datasetId}/fields';
export const DATASET_RESULT_URL = '/_bi_datasets/{datasetId}/result';
export const CONNECTIONS_TYPED_QUERY_URL = '/_bi_connections/{connectionId}/typed_query';
export const CONNECTIONS_TYPED_QUERY_RAW_URL = '/_bi_connections/{connectionId}/typed_query_raw';
export const CONNECTIONS_DASHSQL = '/_bi_connections/{connectionId}/dashsql';
export const CONNECTIONS_DASHSQL_WITH_EXPORT_INFO =
    '/_bi_connections/{connectionId}/dashsql?with_export_info=true';
