import {DATASET_FIELD_TYPES} from 'shared';

export const emptyQaDialogTypes = [
    DATASET_FIELD_TYPES.STRING,
    DATASET_FIELD_TYPES.GENERICDATETIME,
    DATASET_FIELD_TYPES.DATE,
    DATASET_FIELD_TYPES.BOOLEAN,
    DATASET_FIELD_TYPES.UNSUPPORTED,
];
