export const GALLERY_ITEM_CATEGORY = {
    EDITOR: 'editor',
    EDUCATION: 'education',
    FINANCE: 'finance',
    GEO: 'geo',
    HEALTHCARE: 'healthcare',
    HR: 'hr',
    IT: 'it',
    MARKETING: 'marketing',
    MARKETPLACE: 'marketplace',
    PHARMA: 'pharma',
    PRODUCT: 'product',
    PRODUCTION: 'production',
    RETAIL: 'retail',
    SALES: 'sales',
    SERVICE: 'service',
    SOCIAL: 'social',
    SPORTS: 'sport',
    HORECA: 'horeca',
    ENGLISH: 'english',
    TECH: 'tech',
} as const;
