export const getIllustrationStore = () => ({
    light: {
        notFound: () => import('assets/images/illustration/light/404.svg'),
        notFoundError: () => import('assets/images/illustration/light/404.svg'),
        noAccess: () => import('assets/images/illustration/light/403.svg'),
        error: () => import('assets/images/illustrations/light/500.svg'),
        identity: () => import('assets/images/illustrations/light/no_permission.svg'),
        project: () => import('assets/images/illustrations/light/project.svg'),
        template: () => import('assets/images/illustrations/light/empty_state.svg'),
        emptyDirectory: () => import('assets/images/illustrations/light/empty_directory.svg'),
        successOperation: () => import('assets/images/illustrations/light/success_operation.svg'),
        badRequest: () => import('assets/images/illustrations/light/bad_request.svg'),
        noAccounts: () => import('assets/images/illustrations/light/no_accounts.svg'),
    },
    dark: {
        notFound: () => import('assets/images/illustration/dark/404.svg'),
        notFoundError: () => import('assets/images/illustration/dark/404.svg'),
        noAccess: () => import('assets/images/illustration/dark/403.svg'),
        error: () => import('assets/images/illustration/dark/500.svg'),
        identity: () => import('assets/images/illustrations/dark/no_permission.svg'),
        project: () => import('assets/images/illustrations/dark/project.svg'),
        template: () => import('assets/images/illustrations/dark/empty_state.svg'),
        emptyDirectory: () => import('assets/images/illustrations/dark/empty_directory.svg'),
        successOperation: () => import('assets/images/illustrations/dark/success_operation.svg'),
        badRequest: () => import('assets/images/illustrations/dark/bad_request.svg'),
        noAccounts: () => import('assets/images/illustrations/dark/no_accounts.svg'),
    },
});
