export const SET_SERVICE_USERS_LIST_SUCCESS = Symbol('serviceUsers/SET_SERVICE_USERS_LIST_SUCCESS');
export const SET_SERVICE_USERS_LIST_LOADING = Symbol('serviceUsers/SET_SERVICE_USERS_LIST_LOADING');
export const SET_SERVICE_USERS_LIST_FAILED = Symbol('serviceUsers/SET_SERVICE_USERS_LIST_FAILED');
export const RESET_DISPLAYED_USERS = Symbol('serviceUsers/RESET_DISPLAYED_USERS');
