export const SET_SERVICE_USERS_LIST_SUCCESS = Symbol('serviceUsers/SET_SERVICE_USERS_LIST_SUCCESS');
export const SET_SERVICE_USERS_LIST_LOADING = Symbol('serviceUsers/SET_SERVICE_USERS_LIST_LOADING');
export const SET_SERVICE_USERS_LIST_FAILED = Symbol('serviceUsers/SET_SERVICE_USERS_LIST_FAILED');
export const RESET_SERVICE_USERS_LIST = Symbol('serviceUsers/RESET_SERVICE_USERS_LIST');

export const SET_CREATE_USER_SUCCESS = Symbol('serviceUsers/SET_CREATE_USER_SUCCESS');
export const SET_CREATE_USER_LOADING = Symbol('serviceUsers/SET_CREATE_USER_LOADING');
export const SET_CREATE_USER_FAILED = Symbol('serviceUsers/SET_CREATE_USER_FAILED');
export const RESET_CREATE_USER = Symbol('serviceUsers/RESET_CREATE_USER');

export const SAVE_USERS_STATE_BEFORE_FILTER = Symbol('serviceUsers/SAVE_USERS_STATE_BEFORE_FILTER');
export const RESTORE_USERS_STATE_AFTER_FILTER = Symbol(
    'serviceUsers/RESTORE_USERS_STATE_AFTER_FILTER',
);
