export const ControlQA = {
    showInnerTitleCheckbox: 'show-inner-title-checkbox',
    showLabelCheckbox: 'show-control-name-checkbox',
    controlLabel: 'chartkit-control-title',
    controlSelect: 'chartkit-control-select',
    controlSelectItems: 'chartkit-control-select-items',
    controlInput: 'chartkit-control-input',
    inputInnerLabelControl: 'control-inner-label-input',
    inputNameControl: 'control-name-input',
    controlLinks: 'dashkit-overlay-control-links',
    controlMenu: 'dashkit-overlay-control-menu',
    controlSettings: 'dashkit-overlay-control-settings',
    dialogControl: 'dialog-control',
    dialogControlApplyBtn: 'control-dialog-apply-button',
    dialogControlCancelBtn: 'control-dialog-cancel-button',
    selectAcceptable: 'select-acceptable',
    selectAcceptableInput: 'select-acceptable-input',
    selectAcceptableButton: 'select-acceptable-button',
    selectAcceptableItem: 'select-acceptable-item',
    selectAcceptableRemoveButton: 'select-acceptable-remove',
    chartkitControl: 'chartkit-control',
    selectDefaultAcceptable: 'select-default-acceptable',
    acceptableDialogButton: 'acceptable-dialog-button',
};
