export const enum VisualizationsQa {
    Line = 'visualization-item-line',
    Area = 'visualization-item-area',
    Area100p = 'visualization-item-area100p',
    Column = 'visualization-item-column',
    Column100p = 'visualization-item-column100p',
    Bar = 'visualization-item-bar',
    Bar100p = 'visualization-item-bar100p',
    Scatter = 'visualization-item-scatter',
    Pie = 'visualization-item-pie',
    Donut = 'visualization-item-donut',
    Metric = 'visualization-item-metric',
    Treemap = 'visualization-item-treemap',
    FlatTable = 'visualization-item-flatTable',
    PivotTable = 'visualization-item-pivotTable',
    Geolayer = 'visualization-item-geolayer',
    CombinedChart = 'visualization-item-combined-chart',
}
