on:
  workflow_dispatch:
  push:
    branches:
      - build-application-docker-task
      # - 'release-**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: Build Application Docker

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: datalens-ui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Get release build version'
        run: |
          BUILD_VERSION=$(jq -r '.version' package.json)
          echo "Release build version: ${BUILD_VERSION}"
          echo "BUILD_VERSION=$BUILD_VERSION" >> "$GITHUB_ENV"
      - name: Log in to the Container registry
        uses: docker/login-action
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract tags for Docker
        id: meta
        uses: docker/metadata-action
        with:
          # type=raw,value=${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest
          tags: |
            type=raw,value=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_VERSION }}
      - name: Build and push Docker image
        uses: docker/build-push-action
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
