name: Tracker ticket PR merged

on:
  push:
    branches:
      - 'release-**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: tracker-ticket-pr-merged
    runs-on:
      - self-hosted
      - linux
      - qyp
    steps:
      - uses: actions/checkout@v4
      - name: pr merged ticket status
        run: scripts/ci/tracker-ticket-pr-merged.sh
        env:
          ST_OAUTH_TOKEN: ${{ secrets.ST_OAUTH_TOKEN }}
          ST_SERVER_ENDPOINT: ${{ vars.ST_SERVER_ENDPOINT }}
          BRANCH_NAME: ${{ github.head_ref }}
          GH_REPO: ${{ github.repository }}
          COMMENT_MESSAGE: ${{ vars.COMMENT_MESSAGE_PR_MERGED }}
