export const RESET_STATE = Symbol('collections/RESET_STATE');

export const GET_COLLECTION_LOADING = Symbol('collections/GET_COLLECTION_LOADING');
export const GET_COLLECTION_SUCCESS = Symbol('collections/GET_COLLECTION_SUCCESS');
export const GET_COLLECTION_FAILED = Symbol('collections/GET_COLLECTION_FAILED');

export const SET_COLLECTION = Symbol('collections/SET_COLLECTION');
export const RESET_COLLECTION = Symbol('collections/RESET_COLLECTION');

export const GET_COLLECTION_CONTENT_LOADING = Symbol('collections/GET_COLLECTION_CONTENT_LOADING');
export const GET_COLLECTION_CONTENT_SUCCESS = Symbol('collections/GET_COLLECTION_CONTENT_SUCCESS');
export const GET_COLLECTION_CONTENT_FAILED = Symbol('collections/GET_COLLECTION_CONTENT_FAILED');

export const GET_ROOT_COLLECTION_PERMISSIONS_LOADING = Symbol(
    'collections/GET_ROOT_COLLECTION_PERMISSIONS_LOADING',
);
export const GET_ROOT_COLLECTION_PERMISSIONS_SUCCESS = Symbol(
    'collections/GET_ROOT_COLLECTION_PERMISSIONS_SUCCESS',
);
export const GET_ROOT_COLLECTION_PERMISSIONS_FAILED = Symbol(
    'collections/GET_ROOT_COLLECTION_PERMISSIONS_FAILED',
);

export const RESET_COLLECTION_CONTENT = Symbol('collections/RESET_COLLECTION_CONTENT');

export const DELETE_COLLECTION_IN_ITEMS = Symbol('collections/DELETE_COLLECTION_IN_ITEMS');
export const DELETE_WORKBOOK_IN_ITEMS = Symbol('collections/DELETE_WORKBOOK_IN_ITEMS');
