const PUBLIC_GALLERY_ROOT_ROUTE = '/gallery';

export const UNIT_ROUTE = {
    ROOT: PUBLIC_GALLERY_ROOT_ROUTE,
    ALL: `${PUBLIC_GALLERY_ROOT_ROUTE}/all`,
    ENTRY: `${PUBLIC_GALLERY_ROOT_ROUTE}/:id`,
};

export const PUBLIC_GALLERY_ROUTES = [UNIT_ROUTE.ROOT, UNIT_ROUTE.ALL, UNIT_ROUTE.ENTRY];
